name: Unit Tests
on: push
jobs:
  go-tests:
    name: Run Go Unit Tests
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v4
        with:
          go-version: 1.20.5

      - name: 'Install and Configure Terraform'
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.4.6
          terraform_wrapper: false

      - name: Setup Terragrunt
        uses: autero1/action-terragrunt@v1.1.0
        with:
          terragrunt_version: 0.43.2
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Download Go Modules
        working-directory: test/src
        run: go mod download

      - name: Run Go Tests
        working-directory: test/src
        run: go test -v -timeout 60m -tags=unit
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
